# docker-compose.yml — CODEANALYST
# Usage: docker compose up -d

services:
  codeanalyst:
    image: docker.io/safrano9999/codeanalyst
    container_name: codeanalyst
    hostname: codeanalyst
    ports:
      - "11000:11000"
    #network_mode: host
    #volumes:
    #  - /:/host:ro
    command: uvicorn webui:app --host 127.0.0.1 --port 11000
    restart: always
    #labels:
    #  - "com.centurylinklabs.watchtower.enable=true"
